### ISSUE TITLE
USER STORY (Frontend): Account registration

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#1]
As a visitor I can register for an account so that I can have a user profile with picture and have full access to the site, make, comment on and like posts and events

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/1

#  Acceptance Criteria

- New users can create user accounts through the sign up form
- User accounts automatically have user profiles associated with them
- Newly registered users are redirected to the sign in form

# Tasks
- [x] Create user sign up form
- [x] Link backend to front so user registration adds new user to db
- [x] Add form validation to ensure data received from sign up form can be stored
- [x] Provide appropriate error messages when account creation is unsuccessful
- [x] Redirect user to log in page following successful registration
