### ISSUE TITLE
USER STORY (Frontend): Log in functionality

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#11]
As a **registered user** I can **log in to my account** so that **I can have full access to the site, make, comment on and like posts and events**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/11

#  Acceptance Criteria
- Registered users can sign in on the sign in page
- If user details are entered incorrectly, users receive appropriate error messages
- When users successfully log in, they are redirected to the main feed page

# Tasks
- [x] Log in form
- [x] Form validation with appropriate error messages
- [x] Redirect user to main feed
