### ISSUE TITLE
USER STORY (Frontend): View user profiles

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#12]
As a **user** I can **view other user's profiles** so that I can **see a specific user's posts and events**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/12

#  Acceptance Criteria
- Users can see other user's individual profile pages
- Profile pages show specific user's posts and events
- Profile pages show counts for comments, followers and events

# Tasks
- [x] Clicking an individual user redirects to the individual profile page
- [x] Profile component renders all relevant profile content
- [x] Post, event and follower counts are displayed with icons
