### ISSUE TITLE
USER STORY (Frontend): Create new event

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#13]
As a **user** I can **create events** so that **I can share information about events with other users**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/13

#  Acceptance Criteria
- Users can create new events
- A new event button brings the user to a new event form
- Submitting the new event form creates a event entry in the db
- Users can see the new event on the list and individual views

# Tasks
- [x] Create “new event” button linking to “new event” page
- [x] Add “new event” form to “new event” page
- [x] Send new event data to db
