### ISSUE TITLE
USER STORY (Frontend): Edit and delete events

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#14]
As a **user** I can **edit or delete my own events** so that **I can fix incorrect information, add more information, or remove the event entirely**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/14

#  Acceptance Criteria
- Users can click “edit event” button which links to “edit event” page
- Users can click “delete event” button which deletes a specific event entry and all associated memories 
- An “edit event” form is rendered on the “edit event” page
- Only the event owner has permission to edit or delete a event

# Tasks
- [x] Display edit and delete buttons next to a event if user is owner
- [x] Add “edit event” form to “edit event” page
- [x] Add permissions so that only event owners can see edit or delete event buttons
