### ISSUE TITLE
USER STORY (Frontend): Like and unlike posts

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#15]
As a **user** I can **like other user's posts** so that **I can show that user I appreciated their content**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/15

#  Acceptance Criteria
- Logged in users can like posts
- Liked posts gain an increase in likes by 1
- Clicking "like" again will remove the like and associated counts
- Logged out users and post owners cannot like a post

# Tasks
- [x] Add like icon to posts
- [x] Clicking like increaes count on post by 1 and turns heart solid
- [x] Clicking again removes 1 from counts and makes heart outline only
- [x] Only logged in users who are not the post owner can like posts
