### ISSUE TITLE
USER STORY (Frontend): Add comments to posts

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#16]
As a **user** I can **create comments on posts** so that **I can communicate with the poster and other users about the post content**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/16

#  Acceptance Criteria
- Logged in users can add comments to posts
- A comment form is rendered on the individual post page
- The comment count for posts with comments increases by one for each comment
- Logged out users cannot leave comments

# Tasks
- [x] Add comment icon to posts
- [x] Render comment form on post page if logged in
- [x] Only logged in users can comment on posts
