### ISSUE TITLE
USER STORY (Frontend): Watch and unwatch events

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#18]
As a **user** I can **watch/unwatch other user's posts** so that **it is added to my watched events list**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/18

#  Acceptance Criteria
- Logged in users can click "watch" events which adds them to their watch list
- Watched events gain an increase in watchers by 1
- Clicking "watch" again will remove the watch and associated counts
- Logged out users and post owners cannot watch an event

# Tasks
- [x] Add watch icon to posts
- [x] Clicking watch increaes count on event by 1 and turns icon solid
- [x] Clicking again removes 1 from counts and makes icon outline only
- [x] Only logged in users who are not the event owner can like posts
