### ISSUE TITLE
USER STORY (Frontend): Watched events page

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#19]
As a **user** I can **view my watched events on a seperate page** so that **I can keep an eye on the event and easily find it again**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/19

#  Acceptance Criteria
- Add route for watched events page (FE)
- Add filters for watched events (API)
- Add watched events button which redirects to watched events page

# Tasks
- [x] Add icon for watched events page
- [x] Add route to watched events page
- [x] Apply filters so only watched events show on page
