### ISSUE TITLE
USER STORY (Frontend): View posts as a visitor

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#2]
As a **visitor** I can **view a list of posts** so that **I can view recent uploads and decide if I want to sign up**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/2

#  Acceptance Criteria
- The list view API endpoints can be viewed by users who are not logged in
- Appropriate permissions allow visitors to view but not create, edit or delete posts
- Clicking an event takes the visitor to the individual post page

# Tasks

- [x] Display all posts with the PostsPage component
- [x] Clicking on a specific post redirects to individual post page
- [x] visitors cannot add, edit or delete posts
