### ISSUE TITLE
USER STORY (Frontend): Calendar assignment on registration

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#20]
As a **user** I am **automatically assigned a calendar** so that **I can easily view my events**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/20

#  Acceptance Criteria
- Calendar automatically generated and linked to user
- Calendar button in navbar takes user to calendar page
- Calendar page renders user's calendar

# Tasks
- [x] User's calendar retrieved from database
- [x] Create calendar component
- [x] Add route to display calendar
- [x] Add calendar icon in navbar
