### ISSUE TITLE
USER STORY (Frontend): Events automatically added to their calendar

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#21]
As a **user**, **the events I create are automatically added to my calendar** so that **I can immediately visualise them**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/21

#  Acceptance Criteria
- Events added automatically to event owner's calendar when created
- Events are filtered so that only owner's events are automatically added
- If event is deleted, it is removed from the calendar

# Tasks
- [x] Owner's events are automatically rendered in the calendar upon creation
- [x] Filter is applied so that only owner's posts are automatically added
- [x] Deleted events are no longer rendered in the calendar
