### ISSUE TITLE
USER STORY (Frontend): Events created by other users can be added to and removed from the calendar

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#22]
As a **user** I can **add and remove other user's events to/from my calendar** so that **I can visually see when they will take place on my personal calendar**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/22

#  Acceptance Criteria
- When users click "add to calendar" on an event it adds that event to their calendar
- When users click "remove from calendar" on an event it removes that event to their calendar
- Only logged in users can add events to their calendar
- If event is deleted, it is removed from the calendar
- Event list is filtered to include these other events

# Tasks
- [x] Add handleAddToCalendar to add the selected event to the calendar of the user who added it
- [x] Add handleRemoveFromCalendar to add the selected event to the calendar of the user who added it
- [x] update the state with setEvents so that the component reloads after adding/removing from calendar
