### ISSUE TITLE
USER STORY (Frontend): Calendar can be viewed as year, month, week and day

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#23]
As a **user** I can **toggle the view of my calendar between year, month, week and day** so that **I can easily visualise my time and see when events are**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/23

#  Acceptance Criteria
- Buttons allow navigation between different calendar views
- Year, month, week and day views are available
- Relevant events are visible in all different views

# Tasks
- [x] Add relevant plugins for FullCalendar
- [x] Add header toolbar buttons for different views
- [x] Add initial month view
