### ISSUE TITLE
USER STORY (Frontend): Scroll through months/weeks/days in calendar

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#24]
As a **user** I can **navigate between days, weeks, months and years using directional arrows** so that **I can easily visualise my events in my calendar**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/24

#  Acceptance Criteria
- Arrow buttons are shown at the top to nagivate between days/weeks/months (depending on view)
- A double arrow is show for navigating through years
- "Today" button automatically takes user back to the current day

# Tasks
- [x] Configure FullCalendar navigation buttons
- [x] Add double arrow for years
- [x] Add today button and configure
