### ISSUE TITLE
USER STORY (Frontend): Calendar day details modal

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#25]
As a **user** I can **click a day and see the events planned for that day** so that **I can quickly see which (if any) events are taking place on a day**

Backend issue:  https://github.com/dragon-fire-fly/organisation_app_api/issues/25

#  Acceptance Criteria
- When user clicks on a day, a modal appears
- Details of events taking place on (or through) that specific day are shown in the modal
- The title of the modal includes the date

# Tasks
- [x] Add an event modal component
- [x] Send relevant props to modal
- [x] Render relevant event details in the event modal
