### ISSUE TITLE
USER STORY (Frontend): Calendar event details modal

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#27]
As a **user** I can **click an event in my calendar to see the event details** so that **I can easily visualise events in my calendar**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/27

#  Acceptance Criteria
- When user clicks on a day, a modal appears
- Details of the specific event clicked are shown in the modal
- The title of the modal includes the event title

# Tasks
- [x] Add an event modal component
- [x] Send relevant props to modal
- [x] Render relevant event details in the event modal
