### ISSUE TITLE
USER STORY (Frontend): Add an event to a post

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#29]
As a **user** I can **choose an event from my event list when I post** so that **I can make a post about that specific event**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/29

#  Acceptance Criteria
- A drop down menu allows users to optionally select an event to add to their post
- A user can select any event from their event list (their own events or ones they've added to calendar)
- In API post has a field called "event" and events have a field called "posts" which are both updated on a new post with associated event

# Tasks
- [x] Add dropdown to PostCreateForm
- [x] Obtain user's event list from API with axios request
- [x] Populate dropdown options from user's event list
- [x] Send the event id with form so the lists can be updated
- [x] Add event (with link to event) to post component if present
