### ISSUE TITLE
USER STORY (Frontend): User profiles feature posts from that specific user

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#30]
As a **user** I can **view specific posts from another user in their profile** so that **I can see that user's post activity**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/30

#  Acceptance Criteria
- When clicking their own or another user's profile, posts from that specific user are shown
- Users can click individual posts to view them in a new window
- 10 posts are shown initially, then more load as the user scrolls

# Tasks
- [ ] Retrieve posts from a specific user with an axios request
- [ ] Map posts so they are rendered individually
- [ ] Add infinite scroll component
