### ISSUE TITLE
USER STORY (Frontend): User profiles feature events from that specific user

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#31]
As a **user** I can **view specific events from another user in their profile** so that **I can see that user's events**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/31

#  Acceptance Criteria
- When clicking their own or another user's profile, events from that specific user are shown
- Users can click individual events to view them in a new window
- 10 events are shown initially, then more load as the user scrolls
- Users can navigate between post and event view on each user's profile

# Tasks
- [ ] Add new page for viewing user's specific events
- [ ] Retrieve events from a specific user with an axios request and map them appropriately
- [ ] Add infinite scroll component
- [ ] Add link to render specific events page from standard user profile
