### ISSUE TITLE
USER STORY (Frontend): Specific page for posts by friends

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#32]
As a **user** I can **see posts made specifically by my friends** so that **I can easily access the posts most relevant to me**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/32

#  Acceptance Criteria
- There is a link in the navbar so user's can quickly access their friend's posts
- Clicking the link redirects the user to their "feed" where their friend's posts are
- Posts are filtered to that only that user's friend's posts are shown

# Tasks
- [ ] Add button in navbar for friend's posts
- [ ] Redirect user to relevant filtered route for friend's posts
- [ ] Display only posts from user's friends
