### ISSUE TITLE
USER STORY (Frontend): Friend's events page

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#34]
As a **user** I can **view my friend's events on a seperate page** so that **I can quickly browse events most relevant to me**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/34

#  Acceptance Criteria
- There is a link in the navbar so user's can quickly access their friend's events
- Clicking the link redirects the user to their "feed" where their friend's events are
- Posts are filtered to that only that user's friend's events are shown

# Tasks
- [x] Add button in navbar for friend's posts
- [x] Redirect user to relevant filtered route for friend's posts
- [x] Display only posts from user's friends
