### ISSUE TITLE
USER STORY (Frontend): Add and remove friends from friends list

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#35]
As a **user** I can **add other users as friends** so that **I can preferentially see their posts and events**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/35

#  Acceptance Criteria
- Users can add other users as friends
- Adding a friend increases the user's "friends" count and the other user's "added by" count by 1
- Once a friend is added, users have the option to remove the friend, reducing the counts by 1

# Tasks
- [x] Add "add/remove friend" button to profile component
- [x] Conditionally render the button depending on if already followed or not
- [x] Clicking the button triggers handleFollow or handleUnfollow functions
