### ISSUE TITLE
USER STORY (Frontend): Friends page

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#36]
As a **user** I can **view all the users I have added as a friend** so that **I can easily see them, access their profile or remove them**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/36

#  Acceptance Criteria
- "Friends" link is available on the navbar
- Clicking the link takes the user to the "friends" page
- The profiles of any added "friends" are displayed on the page

# Tasks
- [x] Add route in App.js to friends page and create Friends component
- [x] Display profile component for each friend with the remove friend button
- [x] Add refresh function so that clicking remove friend button refreshes friends page
