### ISSUE TITLE
USER STORY (Frontend): Popular profiles sidebar

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#37]
As a **user** I can **see popular profiles on the side panel on the posts page** so that **I can decide who to add as a friend**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/37

#  Acceptance Criteria
- A sidebar is rendered on the posts page to show the profiles with the highest follower counts
- Profile component renders the profile picture, username and add/remove friend button
- Sidebar is responsive and becomes a top bar on mobile devices

# Tasks
- [x] Retrieve profiles from API and order by follower count (highest first)
- [x] Create Profile and PopularProfiles components for displaying profiles on sidebar
- [x] Add responsiveness so popular profiles display as sidebar on larger devices and top bar on smaller devices
