### ISSUE TITLE
USER STORY (Frontend): Upcoming events sidebar

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#38]
As a **user** I can **see my upcoming events on a sidebar** so that **I can quickly see which of my events are coming up soon**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/38

#  Acceptance Criteria
- A sidebar is rendered on the events page to show upcoming events for the user
- EventMini component renders the event picture, title and date for each event
- Sidebar is responsive and becomes a top bar on mobile devices

# Tasks
- [x] Retrieve events from API and order FUTURE events by date (soonest first)
- [x] Create EventMini component for displaying events on sidebar
- [x] Add responsiveness so upcoming events display as sidebar on larger devices and top bar on smaller devices
