### ISSUE TITLE
USER STORY (Frontend): View individual posts as a visitor

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#4]
As a **visitor** I can **view individual posts** so that **I can read the post in more detail and see the associated comments**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/4

#  Acceptance Criteria
- The detail view API endpoints can be viewed by users who are not logged in
- Appropriate permissions allow visitors to view but not create, edit or delete posts
- Individual posts have their associated comments visible to visitors

# Tasks
- [x] Display individual posts with the PostPage and Post components
- [x] Visitors cannot edit or delete posts
- [x] Visitors can view comments but not add, edit or delete them
