### ISSUE TITLE
USER STORY (Frontend): Memories

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#40]
As a **user** I can **add memories to past events** so that **I can store my comments and images to look at later**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/40

#  Acceptance Criteria
- Users can add "memories" to events
- Memories may only be added by logged in users
- Memories are displayed on the event's detail page

# Tasks
- [x] Add memories icon to posts
- [x] Render memory form on post page if logged in
- [x] Only logged in users can add memories
