### ISSUE TITLE
USER STORY (Frontend): Edit and delete memories

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#41]
As a **user** I can **edit or delete my own memories** so that **I can fix incorrect information, add more information, or remove the memory entirely**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/41

#  Acceptance Criteria
- User who owns the memory can click “edit memory” button
- An “edit memory” form is rendered on the event page
- A specified memory is deleted when the user clicks the “delete memory” button
- Only the memory owner has permission to edit or delete a memory

# Tasks
- [x] Display edit and delete buttons next to a memory
- [x] Add “edit memory” form to event page
- [x] Add handle edit and handle delete functions
- [x] Add permissions so that only memory owners can see edit or delete buttons
