### ISSUE TITLE
USER STORY (Frontend): Plans

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#42]
As a **user** I can **add plans to future events** so that **I can plan my event more effectively and store useful information together**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/42

#  Acceptance Criteria
- Users can add "plans" to events
- Plans may only be added to events which have not yet taken place
- Plans are displayed on the event's detail page

# Tasks
- [x] Add plans icon to events
- [x] Render plan form on event page if logged in
- [x] Only logged in users can add plans
