### ISSUE TITLE
USER STORY (Frontend): Edit and delete plans

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#43]
As a **user** I can **edit or delete my own plans** so that **I can fix incorrect information, add more information, or remove the plan entirely**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/43

#  Acceptance Criteria
- User who owns the plan can click “edit plan” button
- An “edit plan” form is rendered on the event page
- A specified plan is deleted when the user clicks the “delete plan” button
- Only the plan owner has permission to edit or delete a plan

# Tasks
- [x] Display edit and delete buttons next to a plan
- [x] Add “edit plan” form to event page
- [x] Add permissions so that only plan owners can see edit or delete buttons
