### ISSUE TITLE
USER STORY (Frontend): View plans and memories on each event page

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#44]
As a **user** I can **switch between plans and memories** so that **I can see all information associated with an event**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/44

#  Acceptance Criteria
- Users can switch between plans and memories on individual event pages
- If the event is in the future, my memory becomes a "plan", if the event has already started, it stays a "memory"

# Tasks
- [x] Add a selector switch component to switch between plans and memories
- [x] Render only plans on the plans page and memories on the memories page
- [x] Adjust the placeholder texts and no memory text depending on if the event has started
