### ISSUE TITLE
USER STORY: View individual events as a visitor 

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_frontend#5]
As a **visitor** I can **view individual events** so that **I can see more detail about the event and see any associated comments**

Backend issue: https://github.com/dragon-fire-fly/organisation_app_api/issues/5

#  Acceptance Criteria
- The detail view API endpoints can be viewed by users who are not logged in
- Appropriate permissions allow visitors to view but not create, edit or delete events
- Individual events have their associated comments visible to visitors

# Tasks

- [ ] Display individual events with the EventPage and Event components
- [ ] Visitors cannot edit or delete events
- [ ] Visitors can view comments but not add, edit or delete them
